### PR TITLE
fix(tasks): assign task to connected user

### LINKED ISSUE #17: [OCR]  Une tâche doit être attachée à un utilisateur
Actuellement, lorsqu’une tâche est créée, elle n’est pas rattachée à un utilisateur. Il vous est demandé d’apporter les corrections nécessaires afin qu’automatiquement, à la sauvegarde de la tâche, l’utilisateur authentifié soit rattaché à la tâche nouvellement créée.

Lors de la modification de la tâche, l’auteur ne peut pas être modifié.

Pour les tâches déjà créées, il faut qu’elles soient rattachées à un utilisateur “anonyme”.

### PR DESCRIPTION
**Pull request by JacquesDurand**
closes #17

### CODE REVIEW

File: src/AppBundle/Controller/TaskController.php [hunk 1]
```diff
@@ -31,6 +31,9 @@ public function createAction(Request $request)
         if ($form->isValid()) {
             $em = $this->getDoctrine()->getManager();
 
+            $user = $this->container->get('security.token_storage')->getToken()->getUser();
```
Comment (james2001) [inline src/AppBundle/Controller/TaskController.php:34]: Inject le service

**Review by james2001 — APPROVED** [review]
